/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Printer */

#ifndef _Included_Printer
#define _Included_Printer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Printer
 * Method:    Print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Printer_Print
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
